language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'create database staff_gig_box_test;' -U postgres
test:
  adapter: postgresql
  database: staff_gig_box_test
deploy:
  app: staff-gig-box
  provider: heroku
  api_key:
    secure: Yx1N4B3kW0gkbTgi9/AqSAHDNDvOGx66BXLQQRaYJ4M1KBilZgHAcFPpTTuNJQ8quk3NHLNWfj+VdRmV0tCaDg6hep7odHbaBaPbnuXgNF/cxGBqT8oAxv2zqSB+opQW588AldAyWfdksnammu5tf/w1Zzikj3oyKa2AO8FhuPBJ7oUdMGpH4SNJ0c0dAgP9KAQ6V0zPb6qALr1ls0zdqXoliMgtKrTEY7RMrp/1/lHxwVNXiBgfc+SRZ/eQasGKgpq5V4+86n/Gt94tbZzhZq3uvjHd6tnQPLYbgFaBOeBGq1Lj1LGcCsKU1flkjAHpfwCy1FrTz6CkkAtbzVqjO/qyPvJCNvAZyIVGsKjct3wfV1sjfGAjBMnapJLN41deaC49yDdHuRE2Eu5hq0rhSHREBNpSlCogoE6HVOxeWF72eRmmm11qAxneZ7DFO76FfsfhzHfqFiVamqolArV0mUbLiEyd8niBtlSwTlejLul6TO+ZZq95EkWq3l1KsDMYXjdS1v/d7XWQIaEbONU4qY+ZiIBhcQTsdQdRv1pD5V+0B3V4MZho7kXNZ/EFYACoTOPFcGBCuyJGICdvkVrPka/M0S5SdXnOk0qH8MsW/f1YVA0S7bSonV0R1/UezP0Z3AAwaGSRAVPWNMZY2k06MwC5zqh6WZQ4keJFX9qIQ3s=
notifications:
  email: false
